package com.tuita.sdk.im.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.tuita.sdk.im.db.module.Contact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CONTACT.
*/
public class ContactDao extends AbstractDao<Contact, Long> {

    public static final String TABLENAME = "CONTACT";

    /**
     * Properties of entity Contact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Myid = new Property(1, Long.class, "myid", false, "MYID");
        public final static Property Chat_id = new Property(2, Long.class, "chat_id", false, "CHAT_ID");
        public final static Property Chat_type = new Property(3, Integer.class, "chat_type", false, "CHAT_TYPE");
        public final static Property Comment_name = new Property(4, String.class, "comment_name", false, "COMMENT_NAME");
        public final static Property Nick_name = new Property(5, String.class, "nick_name", false, "NICK_NAME");
        public final static Property Avatar = new Property(6, String.class, "avatar", false, "AVATAR");
        public final static Property Local_order = new Property(7, String.class, "local_order", false, "LOCAL_ORDER");
        public final static Property Phone = new Property(8, String.class, "phone", false, "PHONE");
        public final static Property By1 = new Property(9, String.class, "by1", false, "BY1");
        public final static Property By2 = new Property(10, String.class, "by2", false, "BY2");
        public final static Property Is_news_notify = new Property(11, int.class, "is_news_notify", false, "IS_NEWS_NOTIFY");
    };


    public ContactDao(DaoConfig config) {
        super(config);
    }
    
    public ContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CONTACT' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MYID' INTEGER," + // 1: myid
                "'CHAT_ID' INTEGER," + // 2: chat_id
                "'CHAT_TYPE' INTEGER," + // 3: chat_type
                "'COMMENT_NAME' TEXT," + // 4: comment_name
                "'NICK_NAME' TEXT," + // 5: nick_name
                "'AVATAR' TEXT," + // 6: avatar
                "'LOCAL_ORDER' TEXT," + // 7: local_order
                "'PHONE' TEXT," + // 8: phone
                "'BY1' TEXT," + // 9: by1
                "'BY2' TEXT," +  // 10: by2
                "'IS_NEWS_NOTIFY' INTEGER NOT NULL);"); //11: is_news_notify
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CONTACT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Contact entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long myid = entity.getMyid();
        if (myid != null) {
            stmt.bindLong(2, myid);
        }
 
        Long chat_id = entity.getChat_id();
        if (chat_id != null) {
            stmt.bindLong(3, chat_id);
        }
 
        Integer chat_type = entity.getChat_type();
        if (chat_type != null) {
            stmt.bindLong(4, chat_type);
        }
 
        String comment_name = entity.getComment_name();
        if (comment_name != null) {
            stmt.bindString(5, comment_name);
        }
 
        String nick_name = entity.getNick_name();
        if (nick_name != null) {
            stmt.bindString(6, nick_name);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(7, avatar);
        }
 
        String local_order = entity.getLocal_order();
        if (local_order != null) {
            stmt.bindString(8, local_order);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(9, phone);
        }
 
        String by1 = entity.getBy1();
        if (by1 != null) {
            stmt.bindString(10, by1);
        }
 
        String by2 = entity.getBy2();
        if (by2 != null) {
            stmt.bindString(11, by2);
        }

        stmt.bindLong(12, entity.getIs_news_notify());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Contact readEntity(Cursor cursor, int offset) {
        Contact entity = new Contact( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // myid
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // chat_id
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // chat_type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // comment_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // nick_name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // avatar
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // local_order
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // phone
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // by1
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // by2
            cursor.getInt(offset + 11) // is_news_notify
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Contact entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMyid(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setChat_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setChat_type(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setComment_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNick_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAvatar(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLocal_order(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPhone(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setBy1(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setBy2(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setIs_news_notify(cursor.getInt(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Contact entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Contact entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
