package com.tuita.sdk.im.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.tuita.sdk.im.db.module.ServiceMessageRecent;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SERVICE_MESSAGE_RECENT.
*/
public class ServiceMessageRecentDao extends AbstractDao<ServiceMessageRecent, Long> {

    public static final String TABLENAME = "SERVICE_MESSAGE_RECENT";

    /**
     * Properties of entity ServiceMessageRecent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Myid = new Property(1, long.class, "myid", false, "MYID");
        public final static Property Service_id = new Property(2, long.class, "service_id", false, "SERVICE_ID");
        public final static Property Cate_id = new Property(3, Long.class, "cate_id", false, "CATE_ID");
        public final static Property Service_name = new Property(4, String.class, "service_name", false, "SERVICE_NAME");
        public final static Property Service_avatar = new Property(5, String.class, "service_avatar", false, "SERVICE_AVATAR");
        public final static Property Cate_name = new Property(6, String.class, "cate_name", false, "CATE_NAME");
        public final static Property Cate_avatar = new Property(7, String.class, "cate_avatar", false, "CATE_AVATAR");
        public final static Property Digst = new Property(8, String.class, "digst", false, "DIGST");
        public final static Property Detail_type = new Property(9, Integer.class, "detail_type", false, "DETAIL_TYPE");
        public final static Property Date = new Property(10, Long.class, "date", false, "DATE");
        public final static Property Bubble_num = new Property(11, String.class, "bubble_num", false, "BUBBLE_NUM");
        public final static Property By1 = new Property(12, String.class, "by1", false, "BY1");
        public final static Property By2 = new Property(13, String.class, "by2", false, "BY2");
        public final static Property By3 = new Property(14, String.class, "by3", false, "BY3");
        public final static Property IsshowHistory = new Property(15, int.class, "isshowhistory", false, "ISSHOWHISTORY");
    };


    public ServiceMessageRecentDao(DaoConfig config) {
        super(config);
    }
    
    public ServiceMessageRecentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SERVICE_MESSAGE_RECENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'MYID' INTEGER NOT NULL ," + // 1: myid
                "'SERVICE_ID' INTEGER NOT NULL ," + // 2: service_id
                "'CATE_ID' INTEGER," + // 3: cate_id
                "'SERVICE_NAME' TEXT," + // 4: service_name
                "'SERVICE_AVATAR' TEXT," + // 5: service_avatar
                "'CATE_NAME' TEXT," + // 6: cate_name
                "'CATE_AVATAR' TEXT," + // 7: cate_avatar
                "'DIGST' TEXT," + // 8: digst
                "'DETAIL_TYPE' INTEGER," + // 9: detail_type
                "'DATE' INTEGER," + // 10: date
                "'BUBBLE_NUM' TEXT," + // 11: bubble_num
                "'BY1' TEXT," + // 12: by1
                "'BY2' TEXT," + // 13: by2
                "'BY3' TEXT," + // 14: by3
                "'ISSHOWHISTORY' INTEGER NOT NULL);"); // 15: isShowhistory
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SERVICE_MESSAGE_RECENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ServiceMessageRecent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMyid());
        stmt.bindLong(3, entity.getService_id());
 
        Long cate_id = entity.getCate_id();
        if (cate_id != null) {
            stmt.bindLong(4, cate_id);
        }
 
        String service_name = entity.getService_name();
        if (service_name != null) {
            stmt.bindString(5, service_name);
        }
 
        String service_avatar = entity.getService_avatar();
        if (service_avatar != null) {
            stmt.bindString(6, service_avatar);
        }
 
        String cate_name = entity.getCate_name();
        if (cate_name != null) {
            stmt.bindString(7, cate_name);
        }
 
        String cate_avatar = entity.getCate_avatar();
        if (cate_avatar != null) {
            stmt.bindString(8, cate_avatar);
        }
 
        String digst = entity.getDigst();
        if (digst != null) {
            stmt.bindString(9, digst);
        }
 
        Integer detail_type = entity.getDetail_type();
        if (detail_type != null) {
            stmt.bindLong(10, detail_type);
        }
 
        Long date = entity.getDate();
        if (date != null) {
            stmt.bindLong(11, date);
        }
 
        String bubble_num = entity.getBubble_num();
        if (bubble_num != null) {
            stmt.bindString(12, bubble_num);
        }
 
        String by1 = entity.getBy1();
        if (by1 != null) {
            stmt.bindString(13, by1);
        }
 
        String by2 = entity.getBy2();
        if (by2 != null) {
            stmt.bindString(14, by2);
        }
 
        String by3 = entity.getBy3();
        if (by3 != null) {
            stmt.bindString(15, by3);
        }

        stmt.bindLong(16, entity.getIsShowHistory());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ServiceMessageRecent readEntity(Cursor cursor, int offset) {
        ServiceMessageRecent entity = new ServiceMessageRecent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // myid
            cursor.getLong(offset + 2), // service_id
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // cate_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // service_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // service_avatar
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // cate_name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // cate_avatar
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // digst
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // detail_type
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // date
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // bubble_num
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // by1
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // by2
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // by3
            cursor.getInt(offset + 15) // isShowhistory
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ServiceMessageRecent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMyid(cursor.getLong(offset + 1));
        entity.setService_id(cursor.getLong(offset + 2));
        entity.setCate_id(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setService_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setService_avatar(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCate_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCate_avatar(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDigst(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDetail_type(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setDate(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setBubble_num(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setBy1(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBy2(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBy3(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setIsShowHistory(cursor.getInt(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ServiceMessageRecent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ServiceMessageRecent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
