package com.tuita.sdk.im.db.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.zhongsou.souyue.DontObfuscateInterface;

import java.io.Serializable;

/**
 * Entity mapped to table CATE.
 */
public class Cate implements Serializable,DontObfuscateInterface {

    /**
     * 是否有cateid 常量
     */
    public final static int CATE_NO_CATEID = 0;
    public final static int CATE_HAS_CATEID = 1;

    private Long id;
    private long my_id;
    private long cate_id;
    private String cate_name;
    private String cate_avatar;
    private String digst;
    private int is_has_cateid;
    private int bubble_num;
    private long date;
    private String by1;
    private String by2;
    private String by3;

    public Cate() {
    }

    public Cate(Long id) {
        this.id = id;
    }

    public Cate(Long id, long my_id, long cate_id, String cate_name, String cate_avatar, String digst, int is_has_cateid, int bubble_num, long date, String by1, String by2, String by3) {
        this.id = id;
        this.my_id = my_id;
        this.cate_id = cate_id;
        this.cate_name = cate_name;
        this.cate_avatar = cate_avatar;
        this.digst = digst;
        this.is_has_cateid = is_has_cateid;
        this.bubble_num = bubble_num;
        this.date = date;
        this.by1 = by1;
        this.by2 = by2;
        this.by3 = by3;
    }

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getMy_id() {
        return my_id;
    }

    public void setMy_id(long my_id) {
        this.my_id = my_id;
    }

    public long getCate_id() {
        return cate_id;
    }

    public void setCate_id(long cate_id) {
        this.cate_id = cate_id;
    }

    public String getCate_name() {
        return cate_name;
    }

    public void setCate_name(String cate_name) {
        this.cate_name = cate_name;
    }

    public String getCate_avatar() {
        return cate_avatar;
    }

    public void setCate_avatar(String cate_avatar) {
        this.cate_avatar = cate_avatar;
    }

    public String getDigst() {
        return digst;
    }

    public void setDigst(String digst) {
        this.digst = digst;
    }

    public int getIs_has_cateid() {
        return is_has_cateid;
    }

    public void setIs_has_cateid(int is_has_cateid) {
        this.is_has_cateid = is_has_cateid;
    }

    public int getBubble_num() {
        return bubble_num;
    }

    public void setBubble_num(int bubble_num) {
        this.bubble_num = bubble_num;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

    public String getBy3() {
        return by3;
    }

    public void setBy3(String by3) {
        this.by3 = by3;
    }

}
