package com.tuita.sdk.im.db.module;

import java.io.Serializable;
import com.zhongsou.souyue.DontObfuscateInterface;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIG.
 */
public class Config implements Serializable,DontObfuscateInterface{
	private static final long serialVersionUID = -8226432604303138755L;
	private Long id;
    private long myid;
    private long contact_last_update;
    private int total_message_bubble;
    private int friend_bubble;
    private String by1;
    private String by2;

    public Config() {
    }

    public Config(long id) {
        this.id = id;
    }

    public Config(Long id, long myid, long contact_last_update, int total_message_bubble, int friend_bubble, String by1, String by2) {
        this.id = id;
        this.myid = myid;
        this.contact_last_update = contact_last_update;
        this.total_message_bubble = total_message_bubble;
        this.friend_bubble = friend_bubble;
        this.by1 = by1;
        this.by2 = by2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMyid() {
        return myid;
    }

    public void setMyid(long myid) {
        this.myid = myid;
    }

    public long getContact_last_update() {
        return contact_last_update;
    }

    public void setContact_last_update(long contact_last_update) {
        this.contact_last_update = contact_last_update;
    }

    public Integer getTotal_message_bubble() {
        return total_message_bubble;
    }

    public void setTotal_message_bubble(int total_message_bubble) {
        this.total_message_bubble = total_message_bubble;
    }

    public int getFriend_bubble() {
        return friend_bubble;
    }

    public void setFriend_bubble(int friend_bubble) {
        this.friend_bubble = friend_bubble;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

}
