package com.tuita.sdk.im.db.module;

import java.io.Serializable;
import com.zhongsou.souyue.DontObfuscateInterface;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT.
 */
public class Contact implements Serializable,DontObfuscateInterface{
	/**
	 * 不是搜悦用户
	 */
	public static final int STATUS_IS_NOT_SOUYUE_USER=0;
	/**
	 * 是搜悦用户，不是好友
	 */
	public static final int STATUS_IS_SOUYUE_USER_NOT_FRIEND=1;
	/**
	 * 是搜悦用户，也是好友
	 */
	public static final int STATUS_IS_SOUYUE_USER_AND_FRIEND=2;
	private static final long serialVersionUID = 2098206730313507592L;
	private Long id;
    private long myid;
    private long chat_id;
    private int chat_type;
    private String comment_name;
    private String nick_name;
    private String avatar;
    private String local_order;
    private String phone;
    private int status;
    //------add by zhangliang，重新生成bean 请注意添加，不入数据库
    private String action;//广播事件
    private String catalog;//拼音排序
    private int is_news_notify = 0;
    
    public String getCatalog() {
        return catalog;
    }

    public void setIs_news_notify(int is_news_notify) {
        this.is_news_notify = is_news_notify;
    }

    public int getIs_news_notify() {
        return is_news_notify;
    }

    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	private String by1;
    private String by2;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, long myid, long chat_id, int chat_type, String comment_name, String nick_name, String avatar, String local_order, String phone, String by1, String by2,Integer is_news_notify) {
        this.id = id;
        this.myid = myid;
        this.chat_id = chat_id;
        this.chat_type = chat_type;
        this.comment_name = comment_name;
        this.nick_name = nick_name;
        this.avatar = avatar;
        this.local_order = local_order;
        this.phone = phone;
        this.by1 = by1;
        this.by2 = by2;
        this.is_news_notify = is_news_notify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMyid() {
        return myid;
    }

    public void setMyid(long myid) {
        this.myid = myid;
    }

    public long getChat_id() {
        return chat_id;
    }

    public void setChat_id(long chat_id) {
        this.chat_id = chat_id;
    }

    public int getChat_type() {
        return chat_type;
    }

    public void setChat_type(int chat_type) {
        this.chat_type = chat_type;
    }

    public String getComment_name() {
        return comment_name;
    }

    public void setComment_name(String comment_name) {
        this.comment_name = comment_name;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getLocal_order() {
        return local_order;
    }

    public void setLocal_order(String local_order) {
        this.local_order = local_order;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

}
