package com.tuita.sdk.im.db.module;

import java.io.Serializable;

import com.zhongsou.souyue.DontObfuscateInterface;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP.
 */
public class Group implements Serializable,DontObfuscateInterface{

    /**
	 * 
	 */
	private static final long serialVersionUID = -5290691056206186219L;
	private Long id;
    private long group_id;
    private String group_avatar;
    private String group_nick_name;
    private long self_id;
    private Integer is_nick_set;
    private int is_group_saved;//4.1版 通讯录默认是开启的
    private int is_news_notify;//默认 1是开启0是关闭
    private Integer max_numbers;
    private String by1;
    private String by2;
    private long owner_id;
    private int maxGroupMembers;
    private GroupExtendInfo extendInfo;// 5.2 添加 圈子跳转，所新增的 额外字段

    public GroupExtendInfo getExtendInfo() {
        return extendInfo;
    }

    public void setExtendInfo(GroupExtendInfo extendInfo) {
        this.extendInfo = extendInfo;
    }

    public boolean isMember() {
        return isMember;
    }

    public void setMember(boolean isMember) {
        this.isMember = isMember;
    }

    private boolean isMember;

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getMemberCount() {
        return memberCount;
    }

    public void setMemberCount(int memberCount) {
        this.memberCount = memberCount;
    }

    private String avatar;
    private int memberCount;

    public int getMaxGroupMembers() {
        return maxGroupMembers;
    }

    public void setMaxGroupMembers(int maxGroupMembers) {
        this.maxGroupMembers = maxGroupMembers;
    }



    public Group() {
    }

    public Group(Long id) {
        this.id = id;
    }

    public Group(Long id, long group_id, String group_avatar, String group_nick_name, long self_id, Integer is_nick_set, int is_group_saved, int is_news_notify, Integer max_numbers, String by1, String by2, long owner_id,GroupExtendInfo extendInfo) {
        this.id = id;
        this.group_id = group_id;
        this.group_avatar = group_avatar;
        this.group_nick_name = group_nick_name;
        this.self_id = self_id;
        this.is_nick_set = is_nick_set;
        this.is_group_saved = is_group_saved;
        this.is_news_notify = is_news_notify;
        this.max_numbers = max_numbers;
        this.by1 = by1;
        this.by2 = by2;
        this.owner_id = owner_id;
        this.extendInfo = extendInfo;
    }

    public long getOwner_id() {
		return owner_id;
	}

	public void setOwner_id(long owner_id) {
		this.owner_id = owner_id;
	}

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getGroup_id() {
        return group_id;
    }

    public void setGroup_id(long s) {
        this.group_id = s;
    }

    public String getGroup_avatar() {
        return group_avatar;
    }

    public void setGroup_avatar(String group_avatar) {
        this.group_avatar = group_avatar;
    }

    public String getGroup_nick_name() {
        return group_nick_name;
    }

    public void setGroup_nick_name(String group_nick_name) {
        this.group_nick_name = group_nick_name;
    }

    public long getSelf_id() {
        return self_id;
    }

    public void setSelf_id(long self_id) {
        this.self_id = self_id;
    }

    public Integer getIs_nick_set() {
        return is_nick_set;
    }

    public void setIs_nick_set(Integer is_nick_set) {
        this.is_nick_set = is_nick_set;
    }

    public int getIs_group_saved() {
        return is_group_saved;
    }

    public void setIs_group_saved(int is_group_saved) {
        this.is_group_saved = is_group_saved;
    }

    public int getIs_news_notify() {
        return is_news_notify;
    }

    public void setIs_news_notify(int is_news_notify) {
        this.is_news_notify = is_news_notify;
    }

    public Integer getMax_numbers() {
        return max_numbers;
    }

    public void setMax_numbers(Integer max_numbers) {
        this.max_numbers = max_numbers;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

}
