package com.tuita.sdk.im.db.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table MESSAGE__HISTORY.
 */
public class MessageHistory implements IMessageConst{

	private Long id;
	private long myid;
	private long chat_id;
	private int chat_type;
	private String content;
	private int content_type;
	private long date;
	private long session_order;
	private String uuid;
	private int status;
	private long sender;
	private String by1;
	private String by2;
	private String contentforat;
	private String by3;
	private String by4;     //用作mid
	private Long fileMsgId;
    private String pushFrom;       //推送类型添加

	public Long getFileMsgId() {
		return fileMsgId;
	}

	public void setFileMsgId(Long fileMsgId) {
		this.fileMsgId = fileMsgId;
	}

	private String action;

    public String getServiceJumpData() {
        return serviceJumpData;
    }

    public void setServiceJumpData(String serviceJumpData) {
        this.serviceJumpData = serviceJumpData;
    }

    private String serviceJumpData;  //服务号特殊跳转

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}




	public MessageHistory() {
	}

	public MessageHistory(long id) {
		this.id = id;
	}

	public MessageHistory(long id, long myid, long chat_id, int chat_type, String content, int content_type, long date, long session_order, String uuid, int status, long sender, String by1, String by2, String contentforat, String by3, String by4,Long fileMsgId) {
		this.id = id;
		this.myid = myid;
		this.chat_id = chat_id;
		this.chat_type = chat_type;
		this.content = content;
		this.content_type = content_type;
		this.date = date;
		this.session_order = session_order;
		this.uuid = uuid;
		this.status = status;
		this.sender = sender;
		this.by1 = by1;
		this.by2 = by2;
		this.contentforat = contentforat;
		this.by3 = by3;
		this.by4 = by4;
		this.fileMsgId = fileMsgId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getMyid() {
		return myid;
	}

	public void setMyid(long myid) {
		this.myid = myid;
	}

	public long getChat_id() {
		return chat_id;
	}

	public void setChat_id(long chat_id) {
		this.chat_id = chat_id;
	}

	public int getChat_type() {
		return chat_type;
	}

	public void setChat_type(int chat_type) {
		this.chat_type = chat_type;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getContent_type() {
		return content_type;
	}

	public void setContent_type(int content_type) {
		this.content_type = content_type;
	}

	public long getDate() {
		return date;
	}

	public void setDate(long date) {
		this.date = date;
	}

	public long getSession_order() {
		return session_order;
	}

	public void setSession_order(long session_order) {
		this.session_order = session_order;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public long getSender() {
		return sender;
	}

	public void setSender(long sender) {
		this.sender = sender;
	}

	public String getBy1() {
		return by1;
	}

	public void setBy1(String by1) {
		this.by1 = by1;
	}

	public String getBy2() {
		return by2;
	}

	public void setBy2(String by2) {
		this.by2 = by2;
	}

	public String getContentforat() {
		return contentforat;
	}

	public void setContentforat(String contentforat) {
		this.contentforat = contentforat;
	}

	public String getBy3() {
		return by3;
	}

	public void setBy3(String by3) {
		this.by3 = by3;
	}

	public String getBy4() {
		return by4;
	}

	public void setBy4(String by4) {
		this.by4 = by4;
	}

    public String getPushFrom() {
        return pushFrom;
    }

    public void setPushFrom(String pushFrom) {
        this.pushFrom = pushFrom;
    }

}
