package com.tuita.sdk.im.db.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_MID.
 */
public class MessageMid {

    /** Not-null value. */
    private String mid;
    private long timestamp;

    public MessageMid() {
    }

    public MessageMid(String mid) {
        this.mid = mid;
    }

    public MessageMid(String mid, long timestamp) {
        this.mid = mid;
        this.timestamp = timestamp;
    }

    /** Not-null value. */
    public String getMid() {
        return mid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMid(String mid) {
        this.mid = mid;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

}
