package com.tuita.sdk.im.db.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_RECENT.
 */
public class MessageRecent implements IMessageConst {
	private static final long serialVersionUID = 4422070009611161054L;
    public static final int ITEM_JUMP_IMCHAT = 0;
    public static final int ITEM_JUMP_SERVICE_LIST = 1;

    private Long id;
    private long myid;
    private long chat_id;
    private int chat_type;
    private String content;
    private int content_type;
    private long date;
    private String uuid;
    private int status;
    private int bubble_num;
    private long sender;
    private String by1;
    private String by2;
    private String drafttext;
    private String draftforat;
    private String by3;         //现在用做顶置相关操作    0：非置顶  1：置顶
    private String by4;
    private String by5;
    private String chatAvatar;
    private String chatName;
    private boolean isNotify;
    private int jumpType;   //列表页跳转和显示红点类型判断

    public MessageRecent() {
    }

    public MessageRecent(Long id) {
        this.id = id;
    }

    public MessageRecent(Long id, long myid, Long chat_id, Integer chat_type, String content, Integer content_type, Long date, String uuid, Integer status, Integer bubble_num, Long sender, String by1, String by2, String drafttext, String draftforat, String by3, String by4, String by5) {
        this.id = id;
        this.myid = myid;
        this.chat_id = chat_id;
        this.chat_type = chat_type;
        this.content = content;
        this.content_type = content_type;
        this.date = date;
        this.uuid = uuid;
        this.status = status;
        this.bubble_num = bubble_num;
        this.sender = sender;
        this.by1 = by1;
        this.by2 = by2;
        this.drafttext = drafttext;
        this.draftforat = draftforat;
        this.by3 = by3;
        this.by4 = by4;
        this.by5 = by5;
    }

    public int getJumpType() {
        return jumpType;
    }

    public void setJumpType(int jumpType) {
        this.jumpType = jumpType;
    }

    public String getChatName() {
        return chatName;
    }

    public void setChatName(String chatName) {
        this.chatName = chatName;
    }

    public boolean isNotify() {
        return isNotify;
    }

    public void setNotify(boolean isNotify) {
        this.isNotify = isNotify;
    }

    public String getChatAvatar() {
        return chatAvatar;
    }

    public void setChatAvatar(String chatAvatar) {
        this.chatAvatar = chatAvatar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMyid() {
        return myid;
    }

    public void setMyid(long myid) {
        this.myid = myid;
    }

    public long getChat_id() {
        return chat_id;
    }

    public void setChat_id(long chat_id) {
        this.chat_id = chat_id;
    }

    public int getChat_type() {
        return chat_type;
    }

    public void setChat_type(int chat_type) {
        this.chat_type = chat_type;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getContent_type() {
        return content_type;
    }

    public void setContent_type(int content_type) {
        this.content_type = content_type;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getBubble_num() {
        return bubble_num;
    }

    public void setBubble_num(int bubble_num) {
        this.bubble_num = bubble_num;
    }

    public long getSender() {
        return sender;
    }

    public void setSender(long sender) {
        this.sender = sender;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

    public String getDrafttext() {
        return drafttext;
    }

    public void setDrafttext(String drafttext) {
        this.drafttext = drafttext;
    }

    public String getDraftforat() {
        return draftforat;
    }

    public void setDraftforat(String draftforat) {
        this.draftforat = draftforat;
    }

    public String getBy3() {
        return by3;
    }

    public void setBy3(String by3) {
        this.by3 = by3;
    }

    public String getBy4() {
        return by4;
    }

    public void setBy4(String by4) {
        this.by4 = by4;
    }

    public String getBy5() {
        return by5;
    }

    public void setBy5(String by5) {
        this.by5 = by5;
    }
}
