package com.tuita.sdk.im.db.module;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NEW_FRIEND.
 */
public class NewFriend implements IConst{
	private static final long serialVersionUID = 1905603914904580640L;
	private Long id;
    private long myid;
    private long chat_id;
    private int chat_type;
    private String comment_name;
    private String nick_name;
    private String avatar;
    private int status;
    private String allow_text;
    private String by1;		//现在存储的是手机号
    private String origin;		//来源（搜索、二维码、个人中心等来源添加好友）

    private String by2;		//存储的是好友关系类型

    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }
	/**
	 * 有人加我，显示通过验证
	 */
	public static final int STATUS_ALLOW = 2;
	/**
	 * 已经添加
	 */
	public static final int STATUS_HAS_ADD = 3;
	/**
	 * 我这边显示添加按钮
	 */
	public static final int STATUS_WAITING_ADD = 0;
	/**
	 * 点击添加按钮，我这边显示等待审核
	 */
	public static final int STATUS_WAITING_ALLOW = 1;

    public NewFriend() {
    }

    public NewFriend(Long id) {
        this.id = id;
    }

    public NewFriend(Long id, Long myid, Long chat_id, Integer chat_type, String comment_name, String nick_name, String avatar, Integer status, String allow_text, String by1, String by2, String origin) {
        this.id = id;
        this.myid = myid;
        this.chat_id = chat_id;
        this.chat_type = chat_type;
        this.comment_name = comment_name;
        this.nick_name = nick_name;
        this.avatar = avatar;
        this.status = status;
        this.allow_text = allow_text;
        this.by1 = by1;
        this.by2 = by2;
        this.origin = origin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMyid() {
        return myid;
    }

    public void setMyid(long myid) {
        this.myid = myid;
    }

    public long getChat_id() {
        return chat_id;
    }

    public void setChat_id(long chat_id) {
        this.chat_id = chat_id;
    }

    public int getChat_type() {
        return chat_type;
    }

    public void setChat_type(int chat_type) {
        this.chat_type = chat_type;
    }

    public String getComment_name() {
        return comment_name;
    }

    public void setComment_name(String comment_name) {
        this.comment_name = comment_name;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getAllow_text() {
        return allow_text;
    }

    public void setAllow_text(String allow_text) {
        this.allow_text = allow_text;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

}
