package com.tuita.sdk.im.db.module;

import java.io.Serializable;
import com.zhongsou.souyue.DontObfuscateInterface;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SERVICE_MESSAGE_RECENT.
 */
public class ServiceMessageRecent implements Serializable,DontObfuscateInterface{

    /**
	 * 
	 */
	private static final long serialVersionUID = 3529498146017876273L;
	private Long id;
    private long myid;
    private long service_id;
    private Long cate_id;
    private String service_name;
    private String service_avatar;
    private String cate_name;
    private String cate_avatar;
    private String digst;
    private Integer detail_type;
    private Long date;
    private String bubble_num;
    private String by1;
    private String by2;
    private String by3;     //服务号消息免打扰
    private int isShowHistory;  //5.0新增 服务号增加是否显示查看历史

    public ServiceMessageRecent() {
    }

    public ServiceMessageRecent(Long id) {
        this.id = id;
    }

    public ServiceMessageRecent(Long id, long myid, long service_id, Long cate_id, String service_name, String service_avatar, String cate_name, String cate_avatar, String digst, Integer detail_type, Long date, String bubble_num, String by1, String by2, String by3,int isShowHistory) {
        this.id = id;
        this.myid = myid;
        this.service_id = service_id;
        this.cate_id = cate_id;
        this.service_name = service_name;
        this.service_avatar = service_avatar;
        this.cate_name = cate_name;
        this.cate_avatar = cate_avatar;
        this.digst = digst;
        this.detail_type = detail_type;
        this.date = date;
        this.bubble_num = bubble_num;
        this.by1 = by1;
        this.by2 = by2;
        this.by3 = by3;
        this.isShowHistory = isShowHistory;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMyid() {
        return myid;
    }

    public void setMyid(long myid) {
        this.myid = myid;
    }

    public long getService_id() {
        return service_id;
    }

    public void setService_id(long service_id) {
        this.service_id = service_id;
    }

    public Long getCate_id() {
        return cate_id;
    }

    public void setCate_id(Long cate_id) {
        this.cate_id = cate_id;
    }

    public String getService_name() {
        return service_name;
    }

    public void setService_name(String service_name) {
        this.service_name = service_name;
    }

    public String getService_avatar() {
        return service_avatar;
    }

    public void setService_avatar(String service_avatar) {
        this.service_avatar = service_avatar;
    }

    public String getCate_name() {
        return cate_name;
    }

    public void setCate_name(String cate_name) {
        this.cate_name = cate_name;
    }

    public String getCate_avatar() {
        return cate_avatar;
    }

    public void setCate_avatar(String cate_avatar) {
        this.cate_avatar = cate_avatar;
    }

    public String getDigst() {
        return digst;
    }

    public void setDigst(String digst) {
        this.digst = digst;
    }

    public Integer getDetail_type() {
        return detail_type;
    }

    public void setDetail_type(Integer detail_type) {
        this.detail_type = detail_type;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public String getBubble_num() {
        return bubble_num;
    }

    public void setBubble_num(String bubble_num) {
        this.bubble_num = bubble_num;
    }

    public String getBy1() {
        return by1;
    }

    public void setBy1(String by1) {
        this.by1 = by1;
    }

    public String getBy2() {
        return by2;
    }

    public void setBy2(String by2) {
        this.by2 = by2;
    }

    public String getBy3() {
        return by3;
    }

    public void setBy3(String by3) {
        this.by3 = by3;
    }

    public int getIsShowHistory() {
        return isShowHistory;
    }

    public void setIsShowHistory(int isShowHistory) {
        this.isShowHistory = isShowHistory;
    }

}
