package com.tuita.sdk.im.db.module;

import java.io.Serializable;
import com.zhongsou.souyue.DontObfuscateInterface;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SERVICE_MESSAGE.
 */
public class ServiceMessageChild implements Serializable,DontObfuscateInterface{

    /**
	 * 
	 */
	private static final long serialVersionUID = 4758548039563253459L;
	/**
	 * 
	 */
    private String digst;
    private String pic;
    private String c;

    public ServiceMessageChild() {
    }


    public ServiceMessageChild(String digst, String pic, String c) {
        this.digst = digst;
        this.pic = pic;
        this.c = c;
    }



    public String getDigst() {
        return digst;
    }

    public void setDigst(String digst) {
        this.digst = digst;
    }


	public String getPic() {
		return pic;
	}


	public void setPic(String pic) {
		this.pic = pic;
	}


	public String getC() {
		return c;
	}


	public void setC(String c) {
		this.c = c;
	}



}
