package com.zhongsou.souyue.db.homepage;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeListDaoConfig;
    private final DaoConfig userHomeListDaoConfig;

    private final HomeListDao homeListDao;
    private final UserHomeListDao userHomeListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeListDaoConfig = daoConfigMap.get(HomeListDao.class).clone();
        homeListDaoConfig.initIdentityScope(type);

        userHomeListDaoConfig = daoConfigMap.get(UserHomeListDao.class).clone();
        userHomeListDaoConfig.initIdentityScope(type);

        homeListDao = new HomeListDao(homeListDaoConfig, this);
        userHomeListDao = new UserHomeListDao(userHomeListDaoConfig, this);

        registerDao(HomeList.class, homeListDao);
        registerDao(UserHomeList.class, userHomeListDao);
    }
    
    public void clear() {
        homeListDaoConfig.getIdentityScope().clear();
        userHomeListDaoConfig.getIdentityScope().clear();
    }

    public HomeListDao getHomeListDao() {
        return homeListDao;
    }

    public UserHomeListDao getUserHomeListDao() {
        return userHomeListDao;
    }

}
