package com.zhongsou.souyue.db.homepage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_HOME_LIST.
 */
public class UserHomeList {

    private String userid_identify;
    private String userid;
    private String id_type_time;
    private String read;

    public UserHomeList() {
    }

    public UserHomeList(String userid_identify) {
        this.userid_identify = userid_identify;
    }

    public UserHomeList(String userid_identify, String userid, String id_type_time, String read) {
        this.userid_identify = userid_identify;
        this.userid = userid;
        this.id_type_time = id_type_time;
        this.read = read;
    }

    public String getUserid_identify() {
        return userid_identify;
    }

    public void setUserid_identify(String userid_identify) {
        this.userid_identify = userid_identify;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getId_type_time() {
        return id_type_time;
    }

    public void setId_type_time(String id_type_time) {
        this.id_type_time = id_type_time;
    }

    public String getRead() {
        return read;
    }

    public void setRead(String read) {
        this.read = read;
    }

}
